version: '3.8'

services:
  api:
    build:
      context: ./trackredge-api
      dockerfile: Dockerfile
    container_name: trackredge-api
    volumes:
      - ./trackredge-api:/var/www/html
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_URL=http://localhost:8000
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=trackredge
      - DB_USERNAME=trackredge
      - DB_PASSWORD=trackredge
      - MAIL_MAILER=smtp
      - MAIL_HOST=mailhog
      - MAIL_PORT=1025
      - MAIL_USERNAME=null
      - MAIL_PASSWORD=null
      - MAIL_ENCRYPTION=null
      - MAIL_FROM_ADDRESS=noreply@trackredge.com
      - MAIL_FROM_NAME="TrackrEdge"
    depends_on:
      - db
      - mailhog
    networks:
      - trackredge

  portal:
    image: node:24
    container_name: trackredge-portal
    restart: unless-stopped
    working_dir: /app
    command: bash -c "npm install && npm run start:docker"
    ports:
      - "4200:4200"
    environment:
      - NODE_ENV=development
    volumes:
      - ./trackredge-portal:/app
    networks:
      - trackredge

  db:
    image: postgres:16-alpine
    container_name: trackredge-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=trackredge
      - POSTGRES_USER=trackredge
      - POSTGRES_PASSWORD=trackredge
    volumes:
      - trackredge-db:/var/lib/postgresql/data
    networks:
      - trackredge

  pgadmin:
    image: dpage/pgadmin4
    container_name: trackredge-pgadmin
    restart: unless-stopped
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@trackredge.com
      - PGADMIN_DEFAULT_PASSWORD=trackredge
      - PGADMIN_CONFIG_SERVER_MODE=False
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - db
    networks:
      - trackredge

  mailhog:
    image: mailhog/mailhog
    container_name: trackredge-mailhog
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - trackredge

networks:
  trackredge:
    driver: bridge

volumes:
  trackredge-db:
    driver: local
  pgadmin-data:
    driver: local
  vendor-volume:
    driver: local
